export type AccommodationType =
  | "hotel"
  | "apart"
  | "cabana"
  | "estancia"
  | "lodge"
  | "complejo"
  | "camping"

export type Accommodation = {
  id: string
  name: string
  description: string
  image: string
  modalities: AccommodationType[]
  services: {
    breakfast: boolean
    pool: boolean
    parking: boolean
  }
  fullServices: string[]
  capacity: {
    couples: boolean
    families: boolean
    sportsTeams: boolean
  }
  location: string
  phone?: string
  whatsapp?: string
  instagram?: string
  website?: string
}

export const accommodations: Accommodation[] = [
  {
    id: "hotel-aca-eldorado",
    name: "Hotel ACA Eldorado",
    description:
      "Hotel ACA se encuentra ubicado en la zona céntrica de Eldorado y ofrece servicios recreativos y amplios espacios verdes para el descanso.",
    image: "/images/costanera.png",
    modalities: ["hotel"],
    services: { breakfast: true, pool: true, parking: true },
    fullServices: [
      "WiFi",
      "Aire acondicionado frío/calor",
      "Desayuno buffet",
      "Servicio diario de limpieza",
      "Piscina (abierta todo el año)",
      "Piscina para niños",
      "Gimnasio",
      "Sala de juegos infantiles",
      "Quincho cerrado y salón para eventos",
      "Parrillas al aire libre",
      "Amplio parque con plantas tropicales y árboles autóctonos",
      "Cuna bajo petición",
      "Estacionamiento sin cargo (según disponibilidad)",
    ],
    capacity: { couples: true, families: true, sportsTeams: true },
    location: "Esperanza 480 – Km 9, Eldorado, Misiones",
    phone: "03751-421370",
    whatsapp: "3751-392900",
    instagram: "hotelacaeldorado",
    website: "hotelacaeldorado.com.ar",
  },
  {
    id: "hotel-che-roga",
    name: "Hotel Che Roga",
    description:
      "Hotel Che Roga brinda alojamiento cómodo con instalaciones recreativas y espacios verdes.",
    image: "/images/hero-waterfall.png",
    modalities: ["hotel"],
    services: { breakfast: true, pool: true, parking: true },
    fullServices: [
      "WiFi",
      "Aire acondicionado frío/calor",
      "Desayuno buffet",
      "Servicio diario de limpieza",
      "Piscina con cascada",
      "Sauna húmedo",
      "Gimnasio",
      "Sala de juegos infantiles",
      "Sala de juegos para adultos",
      "Quincho cerrado y quinchos al aire libre",
      "Parque con árboles autóctonos",
      "Biblioteca de autores misioneros",
      "Cunas bajo petición",
      "Estacionamiento sin cargo",
    ],
    capacity: { couples: true, families: true, sportsTeams: true },
    location: "Ruta Nacional 12 km 1540 – Km 6, Eldorado, Misiones",
    phone: "03751-420035",
    whatsapp: "3751-611177",
    instagram: "cherogahotel.eldorado",
    website: "cherogahotel.com",
  },
  {
    id: "hotel-cabanas-san-valentin",
    name: "Hotel Cabañas San Valentín",
    description:
      "Complejo que combina habitaciones de hotel y cabañas equipadas, con servicios gastronómicos y espacios recreativos.",
    image: "/images/saltos-mocona.png",
    modalities: ["hotel", "cabana"],
    services: { breakfast: true, pool: true, parking: true },
    fullServices: [
      "Restaurante",
      "Estacionamiento",
      "Piscina",
      "Juegos para niños",
      "Cabañas totalmente equipadas",
      "WiFi",
      "Aire acondicionado",
      "Blanquería",
      "Garaje",
      "Parrilla",
      "Desayuno en habitaciones",
    ],
    capacity: { couples: true, families: true, sportsTeams: false },
    location: "Ruta Nacional 12 km 1545, Eldorado, Misiones",
    whatsapp: "3751-539599",
    instagram: "sanvalentin.cabanas",
    website: "hotelcabañassanvalentin.com",
  },
  {
    id: "hotel-atlantida",
    name: "Hotel Atlántida",
    description:
      "Alojamiento ubicado sobre la avenida principal de la ciudad, con acceso a comercios y servicios.",
    image: "/images/costanera.png",
    modalities: ["hotel"],
    services: { breakfast: false, pool: true, parking: false },
    fullServices: ["WiFi", "Aire acondicionado", "Servicio de limpieza", "Piscina", "Salón de eventos"],
    capacity: { couples: true, families: true, sportsTeams: true },
    location: "Av. San Martín 716 – Km 7, Eldorado, Misiones",
    phone: "03751-421441 / 422028",
    instagram: "hotelatlantida01",
  },
  {
    id: "hotel-castelar",
    name: "Hotel Castelar",
    description:
      "Hotel ubicado sobre la avenida principal de la ciudad, cercano a comercios y servicios.",
    image: "/images/costanera.png",
    modalities: ["hotel"],
    services: { breakfast: false, pool: false, parking: true },
    fullServices: ["WiFi", "Aire acondicionado", "Estacionamiento", "TV", "Ropa de cama"],
    capacity: { couples: true, families: false, sportsTeams: false },
    location: "Av. San Martín 1010 – Km 8, Eldorado, Misiones",
    phone: "03751-421348",
    instagram: "castelarhotel",
  },
  {
    id: "hotel-315",
    name: "Hotel 315",
    description: "Alojamiento en el centro de la ciudad con servicios básicos para una estadía confortable.",
    image: "/images/costanera.png",
    modalities: ["hotel"],
    services: { breakfast: false, pool: false, parking: true },
    fullServices: ["WiFi", "Aire acondicionado", "Estacionamiento", "TV", "Ropa de cama"],
    capacity: { couples: true, families: false, sportsTeams: false },
    location: "Guimaraes 315 – Km 8, Eldorado, Misiones",
    phone: "03751-422399",
  },
  {
    id: "hotel-la-familia",
    name: "Hotel La Familia",
    description:
      "Hotel de ambiente familiar, con resto bar para disfrutar de una propuesta gastronómica en el lugar.",
    image: "/images/costanera.png",
    modalities: ["hotel"],
    services: { breakfast: false, pool: false, parking: false },
    fullServices: ["WiFi", "Aire acondicionado", "TV", "Ropa de cama", "Servicio de limpieza", "Resto bar"],
    capacity: { couples: true, families: true, sportsTeams: false },
    location: "Av. San Martín 1850 – Km 9, Eldorado, Misiones",
    whatsapp: "3751-406031",
    instagram: "hotelrestobarlafamilia",
  },
  {
    id: "amambay-apart-suite",
    name: "Amambay Apart & Suite",
    description: "Apart con unidades equipadas para estadías turísticas.",
    image: "/images/saltos-mocona.png",
    modalities: ["apart"],
    services: { breakfast: false, pool: true, parking: true },
    fullServices: ["WiFi", "Aire acondicionado", "Cocina equipada", "TV", "Estacionamiento", "Piscina"],
    capacity: { couples: true, families: true, sportsTeams: false },
    location: "Dr. Prieto 376, Eldorado, Misiones",
    phone: "03751-617027",
    instagram: "amambayapart",
  },
  {
    id: "la-citi-apart",
    name: "La Citi Apart",
    description: "Departamentos equipados para estadías en la ciudad de Eldorado.",
    image: "/images/saltos-mocona.png",
    modalities: ["apart"],
    services: { breakfast: false, pool: false, parking: false },
    fullServices: [
      "Departamentos equipados",
      "Aire acondicionado",
      "WiFi",
      "Servicio de limpieza",
      "Ropa de cama",
      "Insumos para desayuno/merienda",
    ],
    capacity: { couples: true, families: true, sportsTeams: false },
    location: "Kennedy 15 – Km 9, Eldorado, Misiones",
    phone: "03751-445014",
  },
  {
    id: "litoral-apart",
    name: "Litoral Apart",
    description: "Complejo de departamentos turísticos.",
    image: "/images/saltos-mocona.png",
    modalities: ["apart"],
    services: { breakfast: false, pool: false, parking: false },
    fullServices: ["Departamentos equipados"],
    capacity: { couples: true, families: true, sportsTeams: false },
    location: "Edison 225 – Km 8, Eldorado, Misiones",
    phone: "03751-499855",
  },
  {
    id: "eldorado-apart",
    name: "Eldorado Apart",
    description:
      "Departamento que combina comodidad y confort, para una estadía placentera.",
    image: "/images/saltos-mocona.png",
    modalities: ["apart"],
    services: { breakfast: false, pool: false, parking: false },
    fullServices: [
      "Departamento totalmente equipado para 4 personas",
      "Aire acondicionado",
      "WiFi",
      "Cocina equipada",
      "Ropa de cama",
      "Toallas",
      "Patio",
    ],
    capacity: { couples: true, families: true, sportsTeams: false },
    location: "Francisco Amann 2084, Eldorado, Misiones",
    phone: "03751-661077",
    instagram: "eldorado.apart",
  },
  {
    id: "posada-de-los-arboles",
    name: "Posada de los Árboles",
    description:
      "Cabañas en el centro de la ciudad, que combinan comodidad urbana con la tranquilidad de la naturaleza.",
    image: "/images/reserva-bird.png",
    modalities: ["cabana"],
    services: { breakfast: false, pool: false, parking: false },
    fullServices: ["Cabañas equipadas", "WiFi", "Aire acondicionado", "Anafe", "Heladera", "Horno", "Pava eléctrica", "Ropa de cama (no incluye toallas)"],
    capacity: { couples: true, families: true, sportsTeams: false },
    location: "San Luis 641 Km 9",
  },
  {
    id: "cabanas-don-juan",
    name: "Cabañas Don Juan",
    description: "Complejo de cabañas con servicios de spa y gimnasio.",
    image: "/images/act-rural.png",
    modalities: ["cabana"],
    services: { breakfast: false, pool: true, parking: true },
    fullServices: ["Aire acondicionado", "WiFi", "Gimnasio", "Spa", "Estacionamiento", "Piscina"],
    capacity: { couples: true, families: true, sportsTeams: true },
    location: "25 de Mayo y Salto Ramirez, Eldorado, Misiones",
    instagram: "hoteldonjuanspa",
  },
  {
    id: "cabanas-camping-la-colina",
    name: "Cabañas Camping La Colina",
    description: "Complejo rodeado de naturaleza que ofrece cabañas y área de camping.",
    image: "/images/act-trekking.png",
    modalities: ["cabana", "camping"],
    services: { breakfast: false, pool: true, parking: true },
    fullServices: ["WiFi", "Aire acondicionado", "Estacionamiento", "Cocina equipada", "TV", "Espacios verdes", "Quinchos", "Parrillas", "Piscina", "Toboganes"],
    capacity: { couples: true, families: true, sportsTeams: true },
    location: "Matienzo 975 – Km 3, Eldorado, Misiones",
    phone: "03751-360006",
  },
  {
    id: "cabanas-camping-la-familia",
    name: "Cabañas Camping La Familia",
    description: "Complejo rodeado de naturaleza que ofrece cabañas y área de camping.",
    image: "/images/act-trekking.png",
    modalities: ["cabana", "camping"],
    services: { breakfast: false, pool: true, parking: false },
    fullServices: ["Cabañas equipadas", "Aire acondicionado", "Heladera", "Ropa de cama", "Quinchos", "Parrillas", "Canchas de futbol y voley", "Piscina"],
    capacity: { couples: false, families: true, sportsTeams: true },
    location: "Pionero Joaquín Schaffer 680, Eldorado, Misiones",
    phone: "03751-501663",
    instagram: "pileta_la_familia",
  },
  {
    id: "cabanas-guayubiras",
    name: "Cabañas Guayubiras",
    description: "Complejo de cabañas ubicado en Eldorado.",
    image: "/images/act-rural.png",
    modalities: ["cabana"],
    services: { breakfast: false, pool: true, parking: false },
    fullServices: ["Cabañas totalmente equipadas para 2, 4 y hasta 7 personas", "Piscina", "Quincho", "Amplio parque"],
    capacity: { couples: true, families: true, sportsTeams: false },
    location: "Calle Maipú s/n, Eldorado, Misiones",
    phone: "03751-507764",
    instagram: "hospedajeeldoradomisiones",
  },
  {
    id: "cabanas-la-quinta",
    name: "Cabañas La Quinta",
    description: "Cabañas para disfrutar y contemplar la naturaleza.",
    image: "/images/act-rural.png",
    modalities: ["cabana"],
    services: { breakfast: false, pool: true, parking: false },
    fullServices: ["Aire acondicionado", "Calefón", "Ropa de cama", "Piscina"],
    capacity: { couples: true, families: true, sportsTeams: false },
    location: "Ruta Provincial 17 Km 12, Eldorado, Misiones",
    phone: "03751-446979",
    instagram: "laquintaeldorado",
  },
  {
    id: "complejo-copacabana",
    name: "Complejo Turístico Copacabana",
    description:
      "Complejo turístico sobre la Ruta Nacional 12, rodeado de naturaleza y pensado para disfrutar de la tranquilidad.",
    image: "/images/hero-waterfall.png",
    modalities: ["complejo", "cabana", "camping"],
    services: { breakfast: false, pool: true, parking: true },
    fullServices: [
      "3 cabañas equipadas para hasta 6 personas",
      "Aire acondicionado",
      "Cocina",
      "Heladera",
      "Ropa de cama",
      "Toallas",
      "Área de camping",
      "Quinchos",
      "Parrillas",
      "Piscinas",
      "Estanque de peces",
      "Cancha de futbol y voley",
      "Proveeduría",
    ],
    capacity: { couples: true, families: true, sportsTeams: true },
    location: "Ruta Nacional 12 km 1546, Eldorado, Misiones",
    phone: "03751-679295",
    instagram: "complejocopacabanaeldorado",
  },
  {
    id: "complejo-panambi-howy",
    name: "Complejo Turístico Panambí Howy",
    description: "Complejo turístico con actividades recreativas.",
    image: "/images/act-kayak.png",
    modalities: ["complejo"],
    services: { breakfast: false, pool: false, parking: false },
    fullServices: ["Cabañas equipadas", "Dormis", "Quincho", "Proveeduría", "Kayak"],
    capacity: { couples: true, families: true, sportsTeams: true },
    location: "Piray Guazú, Eldorado, Misiones",
    phone: "03751-564982",
  },
  {
    id: "cabanas-las-3-morenas",
    name: "Cabañas Las 3 Morenas",
    description:
      "Cabañas Las Tres Morenas es un emprendimiento familiar que propone una experiencia de descanso en contacto con la naturaleza.",
    image: "/images/act-rural.png",
    modalities: ["cabana"],
    services: { breakfast: false, pool: true, parking: false },
    fullServices: ["Cabaña equipada", "Piscina", "Estanque natural", "Áreas verdes"],
    capacity: { couples: true, families: true, sportsTeams: false },
    location: "Av. Juan D. Perón – Km 14, Eldorado, Misiones",
    phone: "03751-666092",
    instagram: "tresmorenas_eldo",
  },
  {
    id: "estancia-las-mercedes",
    name: "Estancia Las Mercedes",
    description:
      "Establecimiento rural que ofrece alojamiento en el casco de la estancia, combinando las comodidades de un hotel con el encanto y el estilo de la década de 1920.",
    image: "/images/act-rural.png",
    modalities: ["estancia"],
    services: { breakfast: true, pool: false, parking: false },
    fullServices: [
      "Aire acondicionado",
      "WiFi",
      "Ropa de cama",
      "Desayuno",
      "Día de campo",
      "Cabalgatas",
      "Kayak",
      "Avistaje de aves",
      "Senderismo",
    ],
    capacity: { couples: true, families: true, sportsTeams: false },
    location: "Av. Córdoba (a 7 km del tránsito pesado), Eldorado, Misiones",
    phone: "03751-479441",
    instagram: "estancia_lasmercedes",
    website: "estancialasmercedes.com",
  },
  {
    id: "rancho-haras-lodge",
    name: "Rancho Haras Lodge",
    description:
      "Cabañas equipadas en establecimiento rural, ideales para descansar y disfrutar de la tranquilidad de la naturaleza.",
    image: "/images/act-rural.png",
    modalities: ["estancia", "cabana"],
    services: { breakfast: false, pool: false, parking: false },
    fullServices: [
      "Cabañas equipadas",
      "Aire acondicionado",
      "WiFi",
      "Ropa de cama",
      "Cabalgatas",
      "Kayak",
      "*No se ofrece desayuno ni servicio gastronómico; las cabañas están equipadas para cocinar",
    ],
    capacity: { couples: true, families: true, sportsTeams: true },
    location: "Picada 16, Eldorado, Misiones",
    phone: "03751-661395",
    instagram: "harasrancholodge",
  },
  {
    id: "cueva-mini-lodge",
    name: "Cueva Miní Lodge",
    description:
      "Lodge en plena selva misionera a orillas del arroyo Piray Miní, ideal para conectar con la naturaleza y realizar actividades de ecoturismo y turismo aventura.",
    image: "/images/cuevas.png",
    modalities: ["lodge", "cabana"],
    services: { breakfast: false, pool: false, parking: true },
    fullServices: [
      "2 cabañas de hasta 3 personas",
      "Aire acondicionado",
      "WiFi",
      "Frigobar",
      "Ropa de cama",
      "1 cabaña de hasta 6 personas",
      "Totalmente equipada",
      "Quincho",
      "Parrilla",
      "Estacionamiento techado",
      "Zona de quinchos con parrillas",
      "Deck",
      "Pontones flotantes",
      "Kayak",
      "Canopy",
      "Paseos en lancha",
      "Paseos en 4x4",
    ],
    capacity: { couples: true, families: true, sportsTeams: true },
    location: "Calle Nolde s/n – Km 3, Eldorado, Misiones",
    phone: "3751-408200",
    instagram: "cuevamini",
  },
  {
    id: "estancia-la-paulina",
    name: "Estancia La Paulina",
    description:
      "Un lugar donde la naturaleza y la tranquilidad se combinan con la calidez de lo familiar. Un espacio pensado para descansar, disfrutar del entorno y vivir una experiencia auténtica en la tierra misionera.",
    image: "/images/act-rural.png",
    modalities: ["estancia", "cabana"],
    services: { breakfast: false, pool: true, parking: true },
    fullServices: [
      "3 Cabañas equipadas con capacidad para hasta 8 personas",
      "Aire acondicionado",
      "WiFi",
      "Estacionamiento",
      "Piscina",
      "Quinchos",
      "Parrillas",
      "Salón de eventos",
      "Cabalgata",
      "Cancha de paddel",
      "Cancha de mini golf",
    ],
    capacity: { couples: true, families: true, sportsTeams: true },
    location: "Paraje Valle Hermoso",
    phone: "3751 604454",
    instagram: "estancialapaulina",
  },
  {
    id: "complejo-ysyry",
    name: "Complejo Ysyry",
    description:
      "Complejo Ysyry ofrece cabañas rodeadas de vegetación. El predio brinda un ambiente tranquilo ideal para descanso, encuentros familiares o eventos, combinando alojamiento con espacios recreativos.",
    image: "/images/act-kayak.png",
    modalities: ["complejo", "cabana", "hotel"],
    services: { breakfast: false, pool: true, parking: true },
    fullServices: [
      "Alojamiento en Cabañas y habitaciones de hotel",
      "Aire acondicionado",
      "WiFi",
      "TV",
      "Estacionamiento",
      "Ropa blanca y ropa de cama",
      "Baño privado",
      "Salón para eventos",
      "Piscinas",
      "Acceso al arroyo Piray Miní",
    ],
    capacity: { couples: true, families: true, sportsTeams: true },
    location: "Ruta Nacional 12 Km 1550 – Colonia Victoria",
    phone: "3751 592663",
    instagram: "complejo.ysyry",
  },
  {
    id: "cabanas-la-querencia",
    name: "Cabañas La Querencia",
    description:
      "Cabañas rodeadas de un entorno natural, ideal para descansar y disfrutar del aire libre.",
    image: "/images/act-rural.png",
    modalities: ["cabana"],
    services: { breakfast: false, pool: true, parking: false },
    fullServices: ["Cabañas equipadas", "Amplio parque", "Piscina", "Estanque de peces bajo la modalidad de pesque y pague"],
    capacity: { couples: true, families: true, sportsTeams: false },
    location: "Santiago de Liniers Km 31",
    phone: "03751-665365",
    instagram: "laquerencia8",
  },
]

export const typeOptions = [
  { value: "hotel", label: "Hotel" },
  { value: "apart", label: "Apart Hotel" },
  { value: "cabana", label: "Cabaña" },
  { value: "estancia", label: "Estancia" },
  { value: "lodge", label: "Lodge" },
  { value: "complejo", label: "Complejo" },
  { value: "camping", label: "Camping" },
] as const

export const serviceOptions = [
  { value: "breakfast", label: "Con desayuno" },
  { value: "pool", label: "Piscina" },
  { value: "parking", label: "Estacionamiento" },
] as const

export const capacityOptions = [
  { value: "couples", label: "Parejas" },
  { value: "families", label: "Familias" },
  { value: "sportsTeams", label: "Contingentes deportivos" },
] as const