export type Experience = {
  id: string
  title: string
  description: string
  image: string
  category: "naturaleza" | "aventura" | "turismo-rural" | "deportes" | "cultura" | "full-day"
  duration: "1h" | "medio-dia" | "dia-completo"
  requiresReservation: boolean
  kidFriendly: boolean
  hasGuide: boolean
}

export const experiences: Experience[] = [
  {
    id: "saltos-mocona",
    title: "Saltos del Moconá",
    description: "Imponentes paredones de agua de más de 10 metros de altura en plena selva misionera.",
    image: "/images/saltos-mocona.png",
    category: "naturaleza",
    duration: "dia-completo",
    requiresReservation: true,
    kidFriendly: true,
    hasGuide: true,
  },
  {
    id: "reserva-delicia",
    title: "Reserva Natural Delicia",
    description: "Conservación y biodiversidad con senderos interpretativos en la selva paranaense.",
    image: "/images/reserva-bird.png",
    category: "naturaleza",
    duration: "medio-dia",
    requiresReservation: false,
    kidFriendly: true,
    hasGuide: true,
  },
  {
    id: "trekking-selva",
    title: "Trekking en la Selva",
    description: "Caminatas guiadas por senderos rodeados de flora y fauna autóctona.",
    image: "/images/act-trekking.png",
    category: "aventura",
    duration: "medio-dia",
    requiresReservation: true,
    kidFriendly: false,
    hasGuide: true,
  },
  {
    id: "kayak-parana",
    title: "Kayak en el Paraná",
    description: "Navegá las aguas del majestuoso río Paraná en una experiencia única.",
    image: "/images/act-kayak.png",
    category: "aventura",
    duration: "1h",
    requiresReservation: true,
    kidFriendly: false,
    hasGuide: true,
  },
  {
    id: "ciclismo-rural",
    title: "Ciclismo Rural",
    description: "Recorré caminos rurales rodeados de plantaciones y naturaleza.",
    image: "/images/act-ciclismo.png",
    category: "turismo-rural",
    duration: "medio-dia",
    requiresReservation: true,
    kidFriendly: true,
    hasGuide: true,
  },
  {
    id: "visita-chacra",
    title: "Visita a Chacras",
    description: "Conocé la producción local, la yerba mate y el trabajo de los colonos.",
    image: "/images/act-rural.png",
    category: "turismo-rural",
    duration: "medio-dia",
    requiresReservation: true,
    kidFriendly: true,
    hasGuide: true,
  },
  {
    id: "torino-mountain",
    title: "Mountain Bike",
    description: "Descensos y senderos para los amantes del deporte sobre ruedas.",
    image: "/images/act-ciclismo.png",
    category: "deportes",
    duration: "1h",
    requiresReservation: true,
    kidFriendly: false,
    hasGuide: false,
  },
  {
    id: "cuevas-santoangel",
    title: "Cuevas de Santo Ángel",
    description: "Aventura y arqueología subterránea en formaciones rocosas milenarias.",
    image: "/images/cuevas.png",
    category: "aventura",
    duration: "medio-dia",
    requiresReservation: true,
    kidFriendly: false,
    hasGuide: true,
  },
  {
    id: "museo-eldorado",
    title: "Museo Cooperativo",
    description: "La historia del trabajo y el esfuerzo de la comunidad de Eldorado.",
    image: "/images/museo.png",
    category: "cultura",
    duration: "1h",
    requiresReservation: false,
    kidFriendly: true,
    hasGuide: true,
  },
  {
    id: "costanera-atardecer",
    title: "Costanera al Atardecer",
    description: "Paseo ideal para disfrutar del río, la gastronomía y los atardeceres.",
    image: "/images/costanera.png",
    category: "full-day",
    duration: "dia-completo",
    requiresReservation: false,
    kidFriendly: true,
    hasGuide: false,
  },
  {
    id: "avistaje-aves",
    title: "Avistaje de Aves",
    description: "Descubrí la increíble diversidad de aves de la selva misionera.",
    image: "/images/act-aves.png",
    category: "naturaleza",
    duration: "1h",
    requiresReservation: true,
    kidFriendly: true,
    hasGuide: true,
  },
  {
    id: "concierto-noche",
    title: "Noche de Conciertos",
    description: "Eventos musicales al aire libre con artistas locales y regionales.",
    image: "/images/eventos-concert.png",
    category: "cultura",
    duration: "dia-completo",
    requiresReservation: false,
    kidFriendly: true,
    hasGuide: false,
  },
  {
    id: "full-day-cataratas",
    title: "Full Day Cataratas",
    description: "Excursión de día completo a las Cataratas del Iguazú desde Eldorado.",
    image: "/images/hero-waterfall.png",
    category: "full-day",
    duration: "dia-completo",
    requiresReservation: true,
    kidFriendly: true,
    hasGuide: true,
  },
  {
    id: "pesca-deportiva",
    title: "Pesca Deportiva",
    description: "Jornada de pesca en los mejores ríos de la región con guía especializado.",
    image: "/images/act-kayak.png",
    category: "deportes",
    duration: "dia-completo",
    requiresReservation: true,
    kidFriendly: false,
    hasGuide: true,
  },
  {
    id: "feria-artesanal",
    title: "Feria de Artesanos",
    description: "Productos regionales, artesanías y gastronomía típica en el centro de la ciudad.",
    image: "/images/costanera.png",
    category: "cultura",
    duration: "1h",
    requiresReservation: false,
    kidFriendly: true,
    hasGuide: false,
  },
]

export const categories = [
  { value: "todas", label: "Todas" },
  { value: "naturaleza", label: "Naturaleza" },
  { value: "aventura", label: "Aventura" },
  { value: "turismo-rural", label: "Turismo rural" },
  { value: "deportes", label: "Deportes" },
  { value: "cultura", label: "Cultura y ciudad" },
  { value: "full-day", label: "Full day" },
] as const

export const durationOptions = [
  { value: "1h", label: "1 hora" },
  { value: "medio-dia", label: "Medio día" },
  { value: "dia-completo", label: "Día completo" },
] as const
